<Project Sdk="Dalamud.NET.Sdk/15.0.0">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Platforms>x64</Platforms>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<UseWindowsForms>false</UseWindowsForms>
		<Version>0.1.44.0</Version>
		<AssemblyVersion>0.1.44.0</AssemblyVersion>
		<FileVersion>0.1.44.0</FileVersion>
		<AssemblyName>CharacterSpawn</AssemblyName>
		<RootNamespace>CharacterSpawn</RootNamespace>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="lz4net" Version="1.0.15.93" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\**\*" />
	</ItemGroup>

	<ItemGroup>
		<None Update="CharacterSpawn.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
